clip_models:
  MNIST:
    symmetric:
      10: 'config25'
      20: 'config24'
      40: 'config3'
      60: 'config23'
      80: 'config13'
    asymmetric:
      40: 'config20'
  
  CIFAR10:
    symmetric:
      10: 'config16'
      20: 'config14'
      40: 'config1'
      60: 'config11'
      80: 'config21'
    asymmetric:
      40: 'config18'

  CIFAR100:
    symmetric:
      10: 'config17'
      20: 'config15'
      40: 'config2'
      60: 'config12'
      80: 'config22'
    asymmetric:
      40: 'config19'



regular_models:
  MNIST:
    scratch:
      symmetric:
        fc1:
          10:
          20:
          40:
          60:
          80:
        resnet18:
          10:
          20:
          40:
          60:
          80:
        resnet34:
          10:
          20:
          40:
          60:
          80:
        resnet50:
          10:
          20:
          40:
          60:
          80:
        resnet101:
          10:
          20:
          40:
          60:
          80:
      asymmetric:
        fc1:
          40:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:

    pretrained:
      symmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:
      asymmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:


  CIFAR10:
    scratch:
      symmetric:
        fc1:
          10:
          20:
          40:
          60:
          80:
        resnet18:
          10:
          20:
          40:
          60:
          80:
        resnet34:
          10:
          20:
          40:
          60:
          80:
        resnet50:
          10:
          20:
          40:
          60:
          80:
        resnet101:
          10:
          20:
          40:
          60:
          80:
      asymmetric:
        fc1:
          40:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:

    pretrained:
      symmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:
      asymmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:

  CIFAR100:
    scratch:
      symmetric:
        fc1:
          10:
          20:
          40:
          60:
          80:
        resnet18:
          10:
          20:
          40:
          60:
          80:
        resnet34:
          10:
          20:
          40:
          60:
          80:
        resnet50:
          10:
          20:
          40:
          60:
          80:
        resnet101:
          10:
          20:
          40:
          60:
          80:
      asymmetric:
        fc1:
          40:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:

    pretrained:
      symmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40:
      asymmetric:
        resnet18:
          40:
        resnet34:
          40:
        resnet50:
          40:
        resnet101:
          40: