clip_models:
  MNIST:
    ho_2:
      symmetric:
        10: 'config37'
        20: 'config38'
        40: 'config39'
        60: 'config40'
        80: 'config41'
      poison: 'config1'
      ic:
        '1-7': 'config2' # numbers
    ho_10:
      symmetric:
        10: 'config25'
        20: 'config24'
        40: 'config3'
        60: 'config23'
        80: 'config13'
      # asymmetric:
      #   40: 'config20'

  CIFAR10:
    ho_2:
      symmetric:
        10: 'config32'
        20: 'config30'
        40: 'config26'
        60: 'config28'
        80: 'config35'
      asymmetric:
        20: 'config44'
        40: 'config42'
      poison: 'config2'
      ic:
        '3-5': 'config1' # cat dog
        '6-9': 'config4' # frog truck


    ho_10:
      symmetric:
        10: 'config16'
        20: 'config14'
        40: 'config1'
        60: 'config11'
        80: 'config21'
      asymmetric:
        40: 'config18'

  CIFAR100:
    ho_2:
      symmetric:
        10: 'config34'
        20: 'config31'
        40: 'config27'
        60: 'config29'
        80: 'config36'
      asymmetric:
        20: 'config45'
        40: 'config43'
      poison: 'config3'
      ic:
        '47-52': 'config3' # maple tre - oak tree
        '0-24': 'config5' # apple cockroach

    ho_10:
      symmetric:
        10: 'config17'
        20: 'config15'
        40: 'config2'
        60: 'config12'
        80: 'config22'
      asymmetric:
        40: 'config19'

DINO:
  MNIST:
    ho_2:
      symmetric:
        40: 'config3'
      # asymmetric:
      #   40:
      # poison: null
  CIFAR10:
    ho_2:
      symmetric:
        40: 'config1'
      asymmetric:
        40: 'config4'
      poison: 'config1'
  CIFAR100:
    ho_2:
      symmetric:
        40: 'config2'
      asymmetric:
        40: 'config5'
      poison: 'config2'



regular_models:
  MNIST:
    scratch:
      ho_2:
        symmetric:
          fc1:
            10: 'config16'
            20: 'config17'
            40: 'config18'
            60: 'config19'
            80: 'config20'
        asymmetric:
          fc1:
            40: 'config31'
        poison:
          fc1: 'config1'
          resnet18: 'config4'


  CIFAR10:
    scratch:
      ho_2:
        symmetric:
          resnet18:
            10: 'config21'
            20: 'config22'
            40: 'config23'
            60: 'config24'
            80: 'config25'
          resnet34:
            40: 'config35'
          resnet50:
            40: 'config37'
          resnet101:
            40: 'config39'
        asymmetric:
          resnet18:
            40: 'config32'
          resnet34:
            40:
          resnet50:
            40:
          resnet101:
            40:
        poison:
          resnet18: 'config2'

    pretrained:
      ho_2:
        symmetric:
          resnet18:
            40: 'config34'
          resnet34:
            40: 'config36'
          resnet50:
            40: 'config38'
          resnet101:
            40: 'config40'
        asymmetric:
          resnet18:
            40:
          resnet34:
            40:
          resnet50:
            40:
          resnet101:
            40:

  CIFAR100:
    scratch:
      ho_2:
        symmetric:
          resnet18:
            10: 'config26'
            20: 'config27'
            40: 'config28'
            60: 'config29'
            80: 'config30'
        asymmetric:
          resnet18:
            40: 'config33'
        poison:
          resnet18: 'config3'
