training_seed: &training_seed 11
dataset_seed: &dataset_seed 11


strategy:
  # finetuning_set: &finetuning_set 'CleanNoiseSplit'
  # percentage: 0.4
  noise:
    set: 'Train'
    noise_rate: 0.4
    noise_type: 'symmetric'
    seed: 8


dataset:
  name: "cifar10"
  num_classes: &num_classes 10
  img_size: [32, 32]
  batch_size: 1024
  subsample_size: [-1, -1]
  class_subset: []
  remap_labels: False
  heldout_conf: null
  grayscale: False
  normalize_imgs: True
  flatten: False
  valset_ratio: 0.0
  num_workers: 8
  seed: *dataset_seed


model:
  type: 'resnet18v2'
  init_channels: 64
  num_classes: *num_classes
  img_size: [32, 32]
  loss_fn: 'CE-NR'
  metrics: ['ACC', 'F1']




trainer:
  max_epochs: &max_epochs 600
  optimizer_cfg: 
    type: "adam"
    lr: 1.0e-4
  # lr_schedule_cfg:
  #   type: 'step'
  #   milestones: [200, 300, 400]
  #   gamma: 0.1
  early_stopping: False
  validation_freq: 1
  save_best_model: True
  checkpoint_freq: -1
  run_on_gpu: True
  use_amp: True
  log_comet: True
  comet_project_name: 'various-experiments'
  seed: *training_seed

  # finetuning:
  #   max_epochs: 600
  #   optimizer_cfg: 
  #     type: "adamw"
  #     lr: 1.0e-4
  #     # betas: [0.9, 0.999]
  #   lr_schedule_cfg:
  #     type: 'cosann'
  #     T_max: *max_epochs
  #     eta_min: 1.0e-6
  #   early_stopping: False
  #   validation_freq: -1
  #   save_best_model: False
  #   checkpoint_freq: -1
  #   run_on_gpu: True
  #   use_amp: True
  #   log_comet: True
  #   comet_project_name: 'pretrain-on-noise'
  #   seed: *training_seed

