training_seed: &training_seed 11
dataset_seed: &dataset_seed 11

datasets:

  - name: "mnist"
    num_classes: 10
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "fashion_mnist"
    num_classes: 10
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "cifar10"
    num_classes: 10
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "cifar100"
    num_classes: 100
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "food101"
    num_classes: 101
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "flowers102"
    num_classes: 102
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed

  - name: "kmnist"
    num_classes: 10
    img_size: [224, 224]
    batch_size: 512
    use_balanced_batch_sampler: True
    valset_ratio: 0.0
    num_workers: 12
    seed: *dataset_seed


model:
  type: 'open_clip_encoder_ViT-B-16'
  pt_weights: 'datacomp_xl_s13b_b90k'
  mlp_proj: True
  proj_dim: 128
  loss_fn:
    type: 'SCL'
    tau: 0.07
    normalize: True
    reduction: 'mean'
    ignore_index: null
  metrics: ['ACC', 'F1']


trainer:
  finetuning:
    max_iterations: 4000
    optimizer_cfg: 
      type: "adamw"
      lr: 1.0e-5
      betas: [0.9, 0.999]
    lr_schedule_cfg:
      type: 'cosann_warmup'
      update_on: 'gradient_step'
      warmup_steps: 200
      T_max: 4000
      eta_min: 1.0e-6
    early_stopping: False
    validation_freq: -1
    save_best_model: False
    checkpoint_freq: -1
    run_on_gpu: True
    use_amp: True
    log_comet: True
    comet_project_name: 'closed_vocab_TA'
    seed: *training_seed

