
training_seed: &training_seed 11
dataset_seed: &dataset_seed 11


strategy:
  finetuning_set: &finetuning_set 'Heldout'
  noise:
    finetuning:
      - set: 'Train'
        noise_rate: 1.0
        noise_type: 'asymmetric'
        seed: 12

dataset:
  name: "clothing1M"
  num_classes: &num_classes 14
  img_size: [224, 224]
  batch_size: 64
  subsample_size: [-1, -1]
  class_subset: []
  remap_labels: False
  grayscale: False
  normalize_imgs: True
  flatten: False
  valset_ratio: 0.0
  num_workers: 8
  seed: *dataset_seed


model:
  type: 'torchvision_resnet50_nonorm'
  pt_weights: 'IMAGENET1K_V2'
  num_classes: *num_classes
  img_size: [224, 224]
  grayscale: False
  loss_fn: 'CE'
  metrics: ['ACC', 'F1']


trainer:
  pretraining:
    max_epochs: &max_epochs 70
    optimizer_cfg: 
      type: "adamw"
      lr: 1.0e-4
      betas: [0.9, 0.999]
    lr_schedule_cfg:
      type: 'step'
      milestones: [30, 40, 50, 55, 60, 65]
      gamma: 0.5
    # lr_schedule_cfg:
    #   type: 'cosann'
    #   T_max: *max_epochs
    #   eta_min: 5.0e-6
    early_stopping: False
    validation_freq: 3
    save_best_model: True
    checkpoint_freq: 3
    run_on_gpu: True
    use_amp: True
    log_comet: True
    comet_project_name: 'realworld-pretrain-on-noise'
    seed: *training_seed

  finetuning:
    max_epochs: 80
    optimizer_cfg: 
      type: "adamw"
      lr: 1.0e-4
      betas: [0.9, 0.999]
    lr_schedule_cfg:
      type: 'step'
      milestones: [40, 50, 60, 70]
      gamma: 0.5
    early_stopping: False
    validation_freq: -1
    save_best_model: False
    checkpoint_freq: -1
    run_on_gpu: True
    use_amp: True
    log_comet: True
    comet_project_name: 'realworld-pretrain-on-noise'
    seed: *training_seed

